FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [   "gunicorn","-w", "4","--timeout", "900","--graceful-timeout", "30","--access-logfile", "-","--error-logfile", "-","-b", "0.0.0.0:8000","app:app"]